### ISSUE TITLE
Supported model list?

### ISSUE THREAD

**Issue by yongwww** [pytorch/tvm#70]
Could you guys share the supported model list? I saw ResNet was supported, am wondering if Inception/MobileNet/VGG/DenseNet/SSD/Mask-RCNN is supported.

**Comment by bwasti** [comment]
We're largely focusing on operators rather than tracking full model coverage. This means most models that use common operators are partially supported as it stands, but may not have completely been covered by TVM's codegen.  The goal at this point is accelerating common workloads rather than supporting the long tail of operators used in all models.

For mobile use-cases this means many models aren't fully exportable with the TVM toolchain.  If you'd like to share any findings on what works/doesn't (it is simple to test a model being fully covered using `torch_tvm.to_relay(model, inputs)`), I'd be happy to add those to the readme 😃
